Soft-Craft-Tech/pamba-web-client

app/components/core/buttons/startTrial.js, app/components/features/home/ctaSection.js, app/components/features/userAccount/shared/sideBarHamburger.js, app/components/features/userAccount/shared/sideNavigation.js, app/components/features/userAccount/shared/sidebarLink.js, app/context/userAccount/userAccountSharedContext.js, app/user/[slug]/layout.js
Merge Dashboard Responsiveness
=> Dashboard Responsiveness

app/api/requests.ts, app/booking/find-services/page.tsx, components/AddServices.tsx, components/Explorer.tsx, components/FindShopsCards.tsx, components/features/profileCompletion/addServices.tsx, components/forms/addServicesForm.tsx, components/tables/expensesTable.tsx, store/displaySlice.ts, store/store.ts, utils/endpoints/auth.ts
- Add Toast Messages Errors
- Close Services Form after Success POST
- N/A
=> Fix: Fix Services Page In Dashboard

store/rootReducer.ts, store/store.ts
- Separate rootReducer to separate individual file
- N/A
=> refactor: separate rootReducer to separate individual file

app/api/businesses.ts, app/user/dashboard/page.tsx, components/features/userAccount/dashboard/overview.tsx, utils/endpoints/businessesEndpoints.ts
- Add business analysis endpoint for dashboard Overview component to fetch data
- N/A
=> refactor: add business analysis endpoint for dashboard Overview component to fetch data

app/api/staff.ts, app/user/dashboard/page.tsx, components/charts/chartCard.tsx, components/charts/financialsummary.tsx, components/tables/staffTable.tsx, utils/endpoints/staffEndpoints.ts
- Update AppointmentsCard component and FinancialSummary component to accept lifetime_expenses and lifetime_sales as props
- N/A
=> refactor: update AppointmentsCard component and FinancialSummary component to accept lifetime_expenses and lifetime_sales as props

app/api/staff.ts, components/tables/staffTable.tsx, utils/endpoints/staffEndpoints.ts
-  Add edit staff API endpoint and functionality
- N/A
=> refactor: add edit staff API endpoint and functionality

app/api/services.ts, app/booking/all-shops/page.tsx, app/booking/find-services/[service]/page.tsx, app/booking/find-services/page.tsx, components/AllShopsHero.tsx, components/Explorer.tsx, components/service-hero.tsx, utils/endpoints/servicesEndpoints.ts
=> fix: Add search functinality

app/api/appointment.ts, app/api/businesses.ts, app/api/staff.ts, app/booking/find-services/[service]/page.tsx, app/booking/find-services/page.tsx, components/AddServices.tsx, components/Explorer.tsx, components/FloaterAppoitment.tsx, components/features/profileCompletion/addServices.tsx, components/features/shop/AboutShop.tsx, utils/endpoints/appointmentsEndpoints.ts
=> Feat find single service

app/booking/find-services/page.tsx, app/globals.css, components/Explorer.tsx, components/FindShopsCards.tsx, components/charts/financialsummary.tsx, components/service-hero.tsx
- Remove background image for small screens to improve responsiveness for find services hero page
- N/A
=> style: improve responsiveness for find services hero page

components/charts/financialsummary.tsx
- Update FinancialSummary component to calculate and update maxYAxisValue for expenses and revenue on the graph
- N/A
=> refactor: Update FinancialSummary component to calculate and update maxYAxisValue for expenses and revenue on the graph

app/globals.css, components/Explorer.tsx, components/FindShopsCards.tsx, components/charts/financialsummary.tsx
- Add swiper for booking FindShopsCards component recommended shops cards on large screens
- N/A
=> feat: add swiper for booking FindShopsCards component recommended shops cards on large screens

components/features/shop/AboutShop.tsx
=> feat: add id on explorer cards

components/FindShopsCards.tsx, components/shared/header/revampedHeader.tsx
=> Fix: Fix Sllider Find Services Page

app/booking/all-shops/page.tsx, app/booking/find-services/[service]/page.tsx, components/Explorer.tsx
=> Feat: Align single service hero image

app/globals.css, app/user/dashboard/page.tsx, components/charts/appointments.tsx, components/charts/financialsummary.tsx, components/features/userAccount/shared/sideBarHamburger.tsx, package-lock.json, package.json
Pass appointments analysis data to AppointmentsTable component and map on graph
- N/A
=> feat: Pass appointments analysis data to AppointmentsTable component and map on graph

app/globals.css, components/charts/financialsummary.tsx, components/features/userAccount/shared/sideBarHamburger.tsx, package-lock.json, package.json
=> Fix: no scrolling the page when the sidebar hamburger is open on small screens

components/charts/financialsummary.tsx
=> fix: Update FinancialSummary component to dynamically calculate maxYAxisValue and display the graph on initial render

app/api/appointment.ts, app/booking/all-shops/page.tsx, components/SingleService.tsx, components/types/index.ts, utils/endpoints/appointmentsEndpoints.ts
=> Fix fitered services

app/user/revenue/page.tsx
Add revenue page with components for financial summary, initial expense states, and revenue table
- N/A
=> feat: Add revenue page with components for financial summary, initial expense states, and revenue table

components/SingleShopHero.tsx, components/calendar/TimeSlots.tsx, components/features/shop/AboutShop.tsx, store/filteredServicesSlice.ts, store/rootReducer.ts, ui/icons/cancel-icon.tsx
- Fix scheduler and single shop view
- N/A
=> Fix: Fix Scheduler timeslots and SIngle Shop View

components/calendar/TimeSlots.tsx
=> Fix week days to display all days of the week

app/user/layout.tsx, components/features/profileCompletion/completed.tsx
=> Align the designs

app/QueryProvider.tsx
=> Fix: Fix authentication persistance in landing page after expiry

app/api/gallery.ts, app/api/reviews.ts, components/SingleService.tsx, components/features/shop/GalleryShop.tsx, components/features/shop/ReviewCard.tsx, components/features/shop/ReviewShop.tsx, components/features/shop/shop-tabs.tsx, components/features/userAccount/shared/sidebarLink.tsx, ui/button.tsx, utils/endpoints/galleryEndpoints.ts, utils/endpoints/index.ts, utils/endpoints/reviewsEndpoints.ts
=> Feat: Complete Book Appointment flow

app/booking/find-services/page.tsx
- Map the changed endpoint correctly
- Fix to search by location and service name
- N/A
=> Fix: Fix Search in Find all Services Page

app/globals.css, app/signup/layout.tsx, components/forms/BusinessInfo.tsx, components/forms/CreateAccount.tsx, tailwind.config.ts
- Aligned the signup page to the figma design
- N/A
=> Align Signup page design

app/user/layout.tsx, app/user/settings/page.tsx, components/AddServices.tsx, components/features/profileCompletion/addServices.tsx, components/features/userAccount/dashboard/overview.tsx, components/features/userAccount/settings/nav.tsx, components/features/userAccount/settings/profileUpdate.tsx, components/features/userAccount/settings/updateForm.tsx, components/features/userAccount/shared/sidebarLink.tsx, components/features/userAccount/shared/userTopBar.tsx, components/forms/addServicesForm.tsx, components/forms/loginForm.tsx, components/tables/expensesTable.tsx
- Fix the mobile responsiveness issues especially on the admin pages.
- Improve User Experience.
- Motivation: KAN-35
- Local test and dev tests successful
- N/A
=> Issue: Fix mobile reponsiveness for admin pages

app/api/appointment.ts, app/api/businesses.ts, app/api/expenses.ts, app/user/dashboard/page.tsx, app/user/expenses/page.tsx, app/user/revenue/page.tsx, app/user/services/page.tsx, components/AddServices.tsx, components/calendar/TimeSlots.tsx, components/charts/appointments.tsx, components/charts/chartCard.tsx, components/charts/chartSummary.tsx, components/charts/clientManagement.tsx, components/charts/expenseSummary.tsx, components/charts/financialsummary.tsx, components/charts/revenueSummary.tsx, components/features/profileCompletion/addServices.tsx, components/features/userAccount/dashboard/overview.tsx, components/features/userAccount/settings/profileUpdate.tsx, components/forms/addServicesForm.tsx, next.config.js, pnpm-lock.yaml, utils/endpoints/appointmentsEndpoints.ts, utils/endpoints/auth.ts
- Implemented reusable graph component for Dashboard, expenses, Client and Revenue pages
- Graphs had wrong labels and redundant data
- Has been tested locally
- N/A
=> Fix: Appointments Chart

app/api/appointment.ts, app/api/clients.ts, app/api/inventory.ts, app/api/revenue.ts, app/api/services.ts, components/SingleService.tsx, components/SingleShopHero.tsx, components/charts/appointments.tsx, components/charts/chartCard.tsx, components/charts/clientManagement.tsx, components/charts/revenueSummary.tsx, components/tables/clientsTable.tsx, components/tables/inventoryTable.tsx, components/tables/revenueTable.tsx, components/types/index.ts, package.json, pnpm-lock.yaml, ui/FormField.tsx, utils/endpoints/index.ts, utils/endpoints/revenueEndpoints.ts, utils/endpoints/servicesEndpoints.ts, utils/providers/QueryProvider.tsx, utils/zodSchema/index.ts
- Removed Static Appointment data form the dashboard
- Added Select option for appointment dates
- Fixed Add, Delete and Edit revenue actions
- Fixed Revenue Graph
- Implemented Add Client form
- Fixed Client data graph
We had unnecessary static data
- Tested on localhost
- N/A
=> Fix: Dashboard Appointment Card

app/about/page.tsx, app/page.tsx, app/services/layout.tsx, tailwind.config.ts
- Added a `container` tailwind config style for max screen width on non-dashboard pages
- Content was spanning the whole screen on 4k screen layouts
- N/A
=> style: Added max screen width to external pages

app/api/auth.ts, app/api/expenses.ts, app/api/staff.ts, app/client-reset/[redirect]/page.tsx, app/login/layout.tsx, app/request-deletion/layout.tsx, app/request-password-reset/layout.tsx, app/reset-password/[token]/layout.tsx, app/signup/layout.tsx, app/signup/page.tsx, app/user/dashboard/page.tsx, components/AddServices.tsx, components/charts/chartCard.tsx, components/charts/expenseSummary.tsx, components/charts/financialsummary.tsx, components/charts/revenueSummary.tsx, components/features/userAccount/settings/profileUpdate.tsx, components/features/userAccount/settings/updateForm.tsx, components/tables/expensesTable.tsx, components/tables/inventoryTable.tsx, components/tables/revenueTable.tsx, components/tables/staffTable.tsx, components/types/index.ts, ui/LabelledFormField.tsx, ui/SelectField.tsx, utils/privateAxios.ts, utils/zodSchema/index.ts
- A lot of changes were made today ✊🏾. My commit messages will have to speak for themselves. 
- We are straightening out some kinks.
- Tests have been done locally.
- N/A
=> Fix: minor bugs throughout the dashboard

app/client-reset/[redirect]/page.tsx, app/user/dashboard/page.tsx, app/user/expenses/page.tsx, components/core/cards/progress.tsx, components/features/profileCompletion/CompleteProfile.tsx, components/features/profileCompletion/addExpenseAccounts.tsx, components/forms/addExpenses.tsx, components/tables/expensesTable.tsx
- Added a modal to pop-up on `/user/dashboard` and `/user/expenses` routes, if user has no expense accounts.
- Removing _add expense account_ on the onboarding page.
- Tested locally
- N/A
=> Feat: Expense modal pop-up

components/SingleService.tsx
- Added opening time on the store service details page (`/booking/find-services/14`)
- Helps user know what time the service is available before booking
- Tested locally
=> Refactor: Added working hours to service details

package.json, pnpm-lock.yaml
=> fix: mui dependency version

app/booking/all-shops/page.tsx, app/user/dashboard/page.tsx, components/forms/fullSignupForm.tsx, components/forms/loginForm.tsx, components/types/index.ts, data/index.ts, utils/auth.ts, utils/privateAxios.ts
- Closes #96 
- Closes #98 
- Partly fixes #92 
- Prevent unnecessary redirect to login page if user isn't verified
- N/A
=> Fix: Auth issues

app/api/businesses.ts, app/user/dashboard/page.tsx, components/forms/fullSignupForm.tsx, utils/endpoints/businessesEndpoints.ts
=> Fix: re-send email verification

app/api/businesses.ts, components/core/cards/progress.tsx
=> Fix:Issue with business image upload

app/api/auth.ts, app/booking/all-shops/page.tsx, app/user/dashboard/page.tsx, components/AllShopsHero.tsx
- Email is now going to be stored in local storage after signup
- Fixed broken location display
- N/A
=> Fix: signup email storage
